print("Введите любую строку:")
my_string=input()
print("Количество символов Вашей строки: ",len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ", ""))
print(my_string[0:1])
print(my_string[-1:])